src/config.rs
This can be done in the template later.
=> Remove "group_by" key

src/command/release_command.rs, tests/common.rs, tests/release_command.rs
Tests and fixes for creating a release.
=> Test: create alpha release

src/cli.rs, src/command/common.rs, src/command/generate_command.rs, src/command/mod.rs, src/command/new_command.rs, src/command/release_command.rs, src/error.rs, src/fragment.rs, src/main.rs, src/template/mod.rs
More individual error types = more good. :laughing:
=> Error refactoring

src/cli.rs, src/command/release_command.rs, src/main.rs
=> Implement --all flag for release subcommand

Cargo.lock, Cargo.toml, src/command/new_command.rs, src/error.rs, src/fragment.rs, src/main.rs
Does not yet feature implementation for list and map.
=> Interactive metadata

Cargo.lock, Cargo.toml, assets/default_config.toml, src/command/new_command.rs, src/error.rs, src/fragment.rs, tests/new_command_creates_default_header.rs
This is the first implementation of metadata crawling.
---
Tests are missing.
=> Metadata crawling

src/cli.rs
Adds some nice CLI enhancements, mostly docs but also a default value for the `--interactive` flag.
=> Cli enhancements

assets/default_config.toml, assets/default_template.handlebars.md
This improves the changelog template a bit concerning whitespace and makes the issue number optional in the default configuration.
=> Template improvements

Cargo.toml
Adds crate metadata for the upcoming release.
=> Crate metadata

.github/dependabot.yml, .github/workflows/flake-update.yml
There's too little progress to have weekly dependency updates.
=> Updates monthly

.changelog.toml, .changelogs/0.1.0/2022-09-18T10_40_28_565776238.md, .changelogs/unreleased/2023-03-02T07_41_23_894605341.md, .changelogs/unreleased/2023-03-02T07_43_21_335297086.md, .changelogs/unreleased/2023-03-03T08_08_41_21078057.md, .changelogs/unreleased/2023-04-28T20_41_56_101798423.md, Cargo.lock, Cargo.toml, assets/default_config.toml, src/cli.rs, src/config.rs, src/error.rs, src/format.rs, src/fragment.rs, tests/generate_command.rs, tests/new_command.rs, tests/new_command_creates_default_header.rs, tests/new_command_editor.rs, tests/release_command.rs, tests/verify_metadata_command.rs
=> Remove YAML from codebase

README.md
Rendered: https://github.com/matthiasbeyer/cargo-changelog/blob/3187732c87f895642c90f81c1455a822e1446682/README.md
=> Expand readme with more info about commands

Cargo.lock, Cargo.toml, src/cli.rs, src/main.rs
=> Add shell autocompletion

.github/workflows/ci.yml
This is not reproducible, lets remove it therefore.
=> Remove deny check

bors.toml
bors does not work anymore, so lets remove it.
=> Remove bors configuration

.changelogs/unreleased/2025-03-29T11_05_47_971055381.md, .changelogs/unreleased/2025-03-29T11_07_12_614021475.md, src/cli.rs, src/command/add_command.rs, src/command/create_release_command.rs, src/command/generate_changelog_command.rs, src/command/has.rs, src/command/mod.rs, src/command/show.rs, src/command/verify_metadata_command.rs, src/error.rs, src/main.rs, src/selector.rs
=> Has command

Cargo.lock, Cargo.toml, src/cli.rs, src/command/add_command.rs, src/command/common.rs, src/command/create_release_command.rs, src/command/generate_changelog_command.rs, src/command/show.rs, src/command/verify_metadata_command.rs, src/main.rs, src/selector.rs, src/util.rs
Add more/better logging capabilities.
=> Add more logging

Cargo.lock, Cargo.toml, src/template/group_by_helper.rs
=> Update dependency: itertools: 0.12 -> 0.14

Cargo.lock, Cargo.toml, src/command/show.rs
=> Update dependency: yanso: 0.5 -> 1

assets/default_template.handlebars.md
=> Allow whitespace before issue number in template

assets/default_config.toml, assets/default_template.handlebars.md, src/template/group_by_helper.rs, tests/generate-changelog.rs
This would fix #374 by adding a default argument to the group header helper
=> Allow default group by header

src/template/indent_helper.rs, src/template/mod.rs, tests/indent_helper.rs
With great help from @TheNeikos
=> Indent helper
